#!/bin/bash
# Generate vectors.h from Berkeley TestFloat-3e (host build). Each line:
#   {op, rm, a, b, z, f}   where f is the expected fflags (SoftFloat's flag byte
#   already matches the RISC-V {NV,DZ,OF,UF,NX} bit layout). b is unused for unary ops.
# op ids must match fputests.c. SoftFloat round-to-int needs -exact so NX is raised.
set -u
# Host-built Berkeley TestFloat-3e generator (override via $TESTFLOAT_GEN).
TF=${TESTFLOAT_GEN:-/home/wtambe/Documents/TestFloat/TestFloat-3e/build/Linux-x86_64-GCC/testfloat_gen}
out=vectors.h
: > "$out"
echo "// auto-generated by gen.sh from Berkeley TestFloat-3e; do not edit." >> "$out"
echo "static const struct vec vectors[] = {" >> "$out"

# emit <op_id> <rm_id> <tf_function> <rm_flag> [extra_flag]
# This SoftFloat build uses the x86 specialization, which returns the "integer
# indeterminate" 0x80000000 for ALL float->int overflow. RISC-V instead SATURATES
# (NaN/+overflow -> max; -overflow -> min). For the f->int ops (op 0,1) we rewrite the
# expected result to the RISC-V value whenever NV (0x10) is set, from the input sign/NaN.
emit() {
	"$TF" "$4" ${5:-} "$3" 2>/dev/null | \
		gawk -v op="$1" -v rm="$2" '{
			a=$1; z=$2; f=$3; fv=strtonum("0x"f);
			if ((op==0 || op==1) && and(fv,0x10)) {
				av=strtonum("0x"a);
				isnan=(and(av,0x7f800000)==0x7f800000) && (and(av,0x007fffff)!=0);
				pos=(and(av,0x80000000)==0);
				if (op==0) z=(isnan||pos)?"7fffffff":"80000000"; # fcvt.w.s
				else       z=(isnan||pos)?"ffffffff":"00000000"; # fcvt.wu.s
			}
			printf "{%s,%s,0x%su,0x0u,0x%su,0x%su},\n", op, rm, a, z, f;
		}' >> "$out"
}

# emit2 <op_id> <rm_id> <tf_function> <rm_flag>   (two-operand: a b z flags)
# RISC-V canonicalizes ANY NaN result to 0x7fc00000 (this SoftFloat uses the x86 NaN),
# so rewrite NaN-valued results.
# Two-operand level-1 sets are huge (~46k/mode minimum, can't subset via -n); decimate
# by a uniform stride (corner cases are interspersed) to keep the embedded binary in range.
ARITH_STRIDE=${ARITH_STRIDE:-8}
emit2() {
	"$TF" "$4" "$3" 2>/dev/null | \
		gawk -v op="$1" -v rm="$2" -v st="$ARITH_STRIDE" '((NR-1) % st)==0 {
			a=$1; b=$2; z=$3; f=$4; zv=strtonum("0x"z);
			if ((and(zv,0x7f800000)==0x7f800000) && (and(zv,0x007fffff)!=0)) z="7fc00000";
			printf "{%s,%s,0x%su,0x%su,0x%su,0x%su},\n", op, rm, a, b, z, f;
		}' >> "$out"
}

# one-operand arith (fsqrt): decimated, NaN result canonicalized.
emit1nan() {
	"$TF" "$4" "$3" 2>/dev/null | \
		gawk -v op="$1" -v rm="$2" -v st="$ARITH_STRIDE" '((NR-1) % st)==0 {
			a=$1; z=$2; f=$3; zv=strtonum("0x"z);
			if ((and(zv,0x7f800000)==0x7f800000) && (and(zv,0x007fffff)!=0)) z="7fc00000";
			printf "{%s,%s,0x%su,0x0u,0x%su,0x%su},\n", op, rm, a, z, f;
		}' >> "$out"
}

# emitcmp <op_id> <tf_function>   (two-operand compare: a b z flags; z is a 0/1 boolean)
# Compares are rounding-mode-independent (emitted once, rm=0) and take no x86/RISC-V rewrite:
# the result is a boolean and the NV semantics are identical -- f32_eq raises NV only on a
# signaling NaN (quiet, == feq.s) while f32_lt/f32_le raise NV on any NaN (== flt.s/fle.s).
emitcmp() {
	"$TF" "$2" 2>/dev/null | \
		gawk -v op="$1" -v st="$ARITH_STRIDE" '((NR-1) % st)==0 {
			printf "{%s,0,0x%su,0x%su,0x%su,0x%su},\n", op, $1, $2, $3, $4;
		}' >> "$out"
}

# Restrict to a subset of op ids via $WANT (space-separated); default = all. Used to run
# one op group at a time at full level-1 coverage (set ARITH_STRIDE=1) without overflowing SRAM.
w(){ case " ${WANT:-0 1 2 3 4 5 6 7 8 9 10 11} " in *" $1 "*) return 0;; esac; return 1; }

for spec in "0 -rnear_even" "1 -rminMag" "2 -rmin" "3 -rmax" "4 -rnear_maxMag"; do
	set -- $spec; rmid="$1"; rmf="$2"
	w 0 && emit 0 "$rmid" f32_to_i32  "$rmf" -exact   # F2IS  fcvt.w.s
	w 1 && emit 1 "$rmid" f32_to_ui32 "$rmf" -exact   # F2IU  fcvt.wu.s
	w 2 && emit 2 "$rmid" i32_to_f32  "$rmf"          # I2FS  fcvt.s.w
	w 3 && emit 3 "$rmid" ui32_to_f32 "$rmf"          # I2FU  fcvt.s.wu
	w 4 && emit2 4 "$rmid" f32_add "$rmf"             # FADD
	w 5 && emit2 5 "$rmid" f32_sub "$rmf"             # FSUB
	w 6 && emit2 6 "$rmid" f32_mul "$rmf"             # FMUL
	w 7 && emit2 7 "$rmid" f32_div "$rmf"             # FDIV
	w 8 && emit1nan 8 "$rmid" f32_sqrt "$rmf"         # FSQRT (one operand)
done

# Compares are rm-independent: emit once (outside the rounding-mode loop), not 5x.
w 9  && emitcmp 9  f32_eq   # FEQ  (quiet:     NV on sNaN only)
w 10 && emitcmp 10 f32_lt   # FLT  (signaling: NV on any NaN)
w 11 && emitcmp 11 f32_le   # FLE  (signaling: NV on any NaN)

echo "};" >> "$out"
echo "vectors.h: $(grep -c '^{' "$out") vectors"
