/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.12.1.454 */
/* Module Version: 5.7 */
/* C:\lscc\diamond\3.12\ispfpga\bin\nt64\scuba.exe -w -n pll_48_to_48_12_24_96__mhz -lang verilog -synth lse -bus_exp 7 -bb -arch sa5p00 -type pll -fin 48 -fclkop 48 -fclkop_tol 0.0 -fclkos 12 -fclkos_tol 0.0 -phases 0 -fclkos2 24 -fclkos2_tol 0.0 -phases2 0 -fclkos3 96 -fclkos3_tol 0.0 -phases3 0 -phase_cntl STATIC -lock -sticky -fb_mode 1 -fdc C:/Users/William Tambe/Documents/Mine/Softcores/fontamsoc/pu32-orangecrab0285/diamond/___/pll_48_to_48_12_24_96_mhz/pll_48_to_48_12_24_96__mhz/pll_48_to_48_12_24_96__mhz.fdc  */
/* Sat Jan 01 15:47:31 2022 */


`timescale 1 ns / 1 ps
module pll_48_to_48_12_24_96_mhz (CLKI, CLKOP, CLKOS, CLKOS2, CLKOS3, 
    LOCK)/* synthesis NGD_DRC_MASK=1 */;
    input wire CLKI;
    output wire CLKOP;
    output wire CLKOS;
    output wire CLKOS2;
    output wire CLKOS3;
    output wire LOCK;

    wire REFCLK;
    wire CLKOS3_t;
    wire CLKOS2_t;
    wire CLKOS_t;
    wire CLKOP_t;
    wire scuba_vhi;
    wire scuba_vlo;

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    defparam PLLInst_0.PLLRST_ENA = "DISABLED" ;
    defparam PLLInst_0.INTFB_WAKE = "DISABLED" ;
    defparam PLLInst_0.STDBY_ENABLE = "DISABLED" ;
    defparam PLLInst_0.DPHASE_SOURCE = "DISABLED" ;
    defparam PLLInst_0.CLKOS3_FPHASE = 0 ;
    defparam PLLInst_0.CLKOS3_CPHASE = 5 ;
    defparam PLLInst_0.CLKOS2_FPHASE = 0 ;
    defparam PLLInst_0.CLKOS2_CPHASE = 23 ;
    defparam PLLInst_0.CLKOS_FPHASE = 0 ;
    defparam PLLInst_0.CLKOS_CPHASE = 47 ;
    defparam PLLInst_0.CLKOP_FPHASE = 0 ;
    defparam PLLInst_0.CLKOP_CPHASE = 11 ;
    defparam PLLInst_0.PLL_LOCK_MODE = 2 ;
    defparam PLLInst_0.CLKOS_TRIM_DELAY = 0 ;
    defparam PLLInst_0.CLKOS_TRIM_POL = "FALLING" ;
    defparam PLLInst_0.CLKOP_TRIM_DELAY = 0 ;
    defparam PLLInst_0.CLKOP_TRIM_POL = "FALLING" ;
    defparam PLLInst_0.OUTDIVIDER_MUXD = "DIVD" ;
    defparam PLLInst_0.CLKOS3_ENABLE = "ENABLED" ;
    defparam PLLInst_0.OUTDIVIDER_MUXC = "DIVC" ;
    defparam PLLInst_0.CLKOS2_ENABLE = "ENABLED" ;
    defparam PLLInst_0.OUTDIVIDER_MUXB = "DIVB" ;
    defparam PLLInst_0.CLKOS_ENABLE = "ENABLED" ;
    defparam PLLInst_0.OUTDIVIDER_MUXA = "DIVA" ;
    defparam PLLInst_0.CLKOP_ENABLE = "ENABLED" ;
    defparam PLLInst_0.CLKOS3_DIV = 6 ;
    defparam PLLInst_0.CLKOS2_DIV = 24 ;
    defparam PLLInst_0.CLKOS_DIV = 48 ;
    defparam PLLInst_0.CLKOP_DIV = 12 ;
    defparam PLLInst_0.CLKFB_DIV = 1 ;
    defparam PLLInst_0.CLKI_DIV = 1 ;
    defparam PLLInst_0.FEEDBK_PATH = "CLKOP" ;
    EHXPLLL PLLInst_0 (.CLKI(CLKI), .CLKFB(CLKOP_t), .PHASESEL1(scuba_vlo), 
        .PHASESEL0(scuba_vlo), .PHASEDIR(scuba_vlo), .PHASESTEP(scuba_vlo), 
        .PHASELOADREG(scuba_vlo), .STDBY(scuba_vlo), .PLLWAKESYNC(scuba_vlo), 
        .RST(scuba_vlo), .ENCLKOP(scuba_vlo), .ENCLKOS(scuba_vlo), .ENCLKOS2(scuba_vlo), 
        .ENCLKOS3(scuba_vlo), .CLKOP(CLKOP_t), .CLKOS(CLKOS_t), .CLKOS2(CLKOS2_t), 
        .CLKOS3(CLKOS3_t), .LOCK(LOCK), .INTLOCK(), .REFCLK(REFCLK), .CLKINTFB())
             /* synthesis FREQUENCY_PIN_CLKOS3="96.000000" */
             /* synthesis FREQUENCY_PIN_CLKOS2="24.000000" */
             /* synthesis FREQUENCY_PIN_CLKOS="12.000000" */
             /* synthesis FREQUENCY_PIN_CLKOP="48.000000" */
             /* synthesis FREQUENCY_PIN_CLKI="48.000000" */
             /* synthesis ICP_CURRENT="11" */
             /* synthesis LPF_RESISTOR="8" */;

    assign CLKOS3 = CLKOS3_t;
    assign CLKOS2 = CLKOS2_t;
    assign CLKOS = CLKOS_t;
    assign CLKOP = CLKOP_t;


    // exemplar begin
    // exemplar attribute PLLInst_0 FREQUENCY_PIN_CLKOS3 96.000000
    // exemplar attribute PLLInst_0 FREQUENCY_PIN_CLKOS2 24.000000
    // exemplar attribute PLLInst_0 FREQUENCY_PIN_CLKOS 12.000000
    // exemplar attribute PLLInst_0 FREQUENCY_PIN_CLKOP 48.000000
    // exemplar attribute PLLInst_0 FREQUENCY_PIN_CLKI 48.000000
    // exemplar attribute PLLInst_0 ICP_CURRENT 11
    // exemplar attribute PLLInst_0 LPF_RESISTOR 8
    // exemplar end

endmodule
